language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t bradley2w1dl/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bradley2w1dl/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react-tut"
  env: "DockerReactTut-env"
  bucket_name: "elasticbeanstalk-us-west-2-797538971579"
  bucket_path: "docker-react-tut"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
